// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AttachProcess(arg1:string,arg2:number):Promise<void>;

export function CancelScript():Promise<void>;

export function DetachProcess():Promise<void>;

export function InjectScript(arg1:string):Promise<void>;

export function ListDevices():Promise<Array<string>>;

export function ListProcessesOfDevice(arg1:string):Promise<Array<main.ProcessInfo>>;
