// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachProcess(arg1, arg2) {
  return window['go']['main']['App']['AttachProcess'](arg1, arg2);
}

export function CancelScript() {
  return window['go']['main']['App']['CancelScript']();
}

export function DetachProcess() {
  return window['go']['main']['App']['DetachProcess']();
}

export function InjectScript(arg1) {
  return window['go']['main']['App']['InjectScript'](arg1);
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function ListProcessesOfDevice(arg1) {
  return window['go']['main']['App']['ListProcessesOfDevice'](arg1);
}
